name: my_device_info
description: "A Flutter plugin to get detailed device info like IMEI, model, API level, CPU type, and more, with full support for Android & iOS."
version: 0.0.1+1
repository: https://github.com/ngmduc2012/my_device_info

environment:
  sdk: ^3.4.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.wongcoupon.my_device_info.my_device_info
        pluginClass: MyDeviceInfoPlugin
      ios:
        pluginClass: MyDeviceInfoPlugin

screenshots:
  - description: "avatar plugin"
    path: avatar.png

topics:
  - device-info
  - imei
  - hardware
  - system-info
  - flutter-plugin
